name: Publish to Maven Central

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Check if version exists
        id: check_version
        run: |
          VERSION=$(./gradlew properties -q | grep "version:" | awk '{print $2}')
          if curl -s "https://repo1.maven.org/maven2/com/learn/smartbot/smartbot/$VERSION/" | grep -q "smartbot-$VERSION"; then
            echo "Version $VERSION already exists in Maven Central"
            exit 1
          fi
      
      - name: Decode GPG key
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}
        run: |
          echo "$GPG_KEY" | base64 -d > private.gpg
      
      - name: Publish to Maven Central
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY: ${{ secrets.GPG_KEY }}
          SIGNING_PASSWORD: ${{ secrets.GPG_PASSWORD }}
        run: ./gradlew publishReleasePublicationToOSSRHRepository 